Listen = "0.0.0.0:5678"
ProxyURL = "http://172.22.11.200:7777"
MysqlDns = "root:12345678@tcp(172.21.0.2:3306)/chatgpt_plus?charset=utf8&collation=utf8_general_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost:8080/static"

[Session]
  Driver = "cookie"
  SecretKey = "8k0c67y2or1n7kbmn1w1c86ygqscguoktuf9t524jm64ls585z8uibpdssiy228s"
  Name = "CHAT_PLUS_SESSION"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin123"

#[Redis]
#  Host = "localhost"
#  Port = 6379
#  Password = ""
